# Generated by Django 4.0.6 on 2023-01-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportesEscolaresSena', '0020_remove_cliente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarios',
            name='documento',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(default='u1', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
